const menu=document.querySelector('.menu'), nav=document.querySelector('.nav nav');
menu?.addEventListener('click',()=>nav.classList.toggle('open'));
document.querySelectorAll('.nav nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));

const data={
wazuh:{title:'Wazuh SOC Home Lab',tag:'SOC / BLUE TEAM',body:`<p class="mono">CASE STUDY / HANDS-ON LAB</p><p>Built a practical SOC environment using Wazuh, an Ubuntu endpoint, Kali Linux and VirtualBox. The lab is used to practice security monitoring, log collection, alert investigation and defensive analysis.</p><h3>What I practiced</h3><ul><li>Wazuh Manager and endpoint monitoring</li><li>Security log collection and alert review</li><li>Investigation of privileged activity</li><li>MITRE ATT&CK technique mapping</li><li>SOC-style documentation and analysis</li></ul><h3>Featured alert</h3><p><strong>Successful sudo to ROOT executed.</strong><br>Rule 5402 · MITRE ATT&CK T1548.003 — Sudo and Sudo Caching</p><p>Exact event details and screenshots will be added from the original lab evidence.</p>`},
yara:{title:'Simple Malware Scanner using YARA',tag:'MALWARE DETECTION',body:`<p class="mono">PROJECT / DETECTION</p><p>A simple malware-scanning project using YARA pattern-matching rules to identify files based on known characteristics and indicators.</p><h3>Focus</h3><ul><li>Writing and understanding YARA rules</li><li>Pattern-based file detection</li><li>Scanning files against detection logic</li><li>Understanding indicators and false positives</li></ul>`},
raptor:{title:'Web Raptor',tag:'WEB SECURITY',body:`<p class="mono">PROJECT / WEB SECURITY</p><p>A cybersecurity project focused on web reconnaissance, information gathering and security assessment concepts.</p><h3>Focus</h3><ul><li>Web reconnaissance</li><li>Information gathering</li><li>Security assessment concepts</li><li>Vulnerability identification</li></ul><p>Project wording intentionally avoids claiming advanced exploitation beyond the work documented.</p>`},
internship:{title:'Cybersecurity Internship',tag:'KAASHIV INFO TECH',body:`<p class="mono">EXPERIENCE / INTERNSHIP</p><p>Cybersecurity internship experience focused on building exposure to common attack types, threat analysis, vulnerabilities, security tools, simulated environments and report documentation.</p><h3>Learning areas</h3><ul><li>Types of cyber attacks</li><li>Threat analysis</li><li>Vulnerability identification</li><li>Cybersecurity tools</li><li>Simulated security environments</li><li>Security documentation</li></ul>`}
};
const modal=document.getElementById('modal'), content=document.getElementById('modal-content');
document.querySelectorAll('.details').forEach(btn=>btn.addEventListener('click',()=>{const d=data[btn.dataset.project];content.innerHTML=`<div class="tag">${d.tag}</div><h2>${d.title}</h2>${d.body}`;modal.classList.add('show');modal.setAttribute('aria-hidden','false')}));
document.querySelector('.close').addEventListener('click',()=>{modal.classList.remove('show');modal.setAttribute('aria-hidden','true')});
modal.addEventListener('click',e=>{if(e.target===modal){modal.classList.remove('show');modal.setAttribute('aria-hidden','true')}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){modal.classList.remove('show');modal.setAttribute('aria-hidden','true')}});
